export type Service = {
  slug: string;
  number: string;
  title: string;
  short: string;
  description: string;
  image: string;
  icon: string;
  subs: string[];
  process: string[];
};

export const services: Service[] = [
  { slug: 'branding', number: '01', title: 'Branding', short: 'Make your brand impossible to ignore.', description: 'We build distinct identities that look sharp, sound human and stay memorable long after the first impression.', image: 'https://images.pexels.com/photos/4271615/pexels-photo-4271615.jpeg?auto=compress&cs=tinysrgb&w=1200', icon: '✦', subs: ['Logo', 'Brand Identity', 'Colors', 'Typography', 'Brand Guidelines'], process: ['Discover the essence', 'Shape the identity', 'Build the system', 'Launch with confidence'] },
  { slug: 'graphic-design', number: '02', title: 'Graphic Design', short: 'Turn every touchpoint into a statement.', description: 'From a social tile to a full campaign world, our design makes every message clearer, bolder and more ownable.', image: 'https://images.pexels.com/photos/4271625/pexels-photo-4271625.jpeg?auto=compress&cs=tinysrgb&w=1200', icon: '◈', subs: ['Social Media Posts', 'Brochures', 'Posters', 'Banners', 'Packaging'], process: ['Find the visual hook', 'Explore the territory', 'Polish every detail', 'Deliver at scale'] },
  { slug: 'advertising', number: '03', title: 'Advertising', short: 'Campaigns people choose to remember.', description: 'Big ideas, smart channels and creative that earns attention without shouting into the void.', image: 'https://images.pexels.com/photos/5488369/pexels-photo-5488369.jpeg?auto=compress&cs=tinysrgb&w=1200', icon: '↗', subs: ['Campaign Concepts', 'Ad Creatives', 'Digital Advertising', 'Traditional Advertising'], process: ['Clarify the opportunity', 'Create the big idea', 'Build the campaign', 'Measure the momentum'] },
  { slug: 'video-production', number: '04', title: 'Video Production', short: 'Move hearts. Move markets.', description: 'Cinematic films, product stories and fast-moving content built for how people watch now.', image: 'https://images.pexels.com/photos/24286930/pexels-photo-24286930.jpeg?auto=compress&cs=tinysrgb&w=1200', icon: '▶', subs: ['Commercial Ads', 'Product Videos', 'Corporate Films', 'Reels'], process: ['Write the story', 'Plan the world', 'Shoot the moment', 'Edit the emotion'] },
  { slug: 'social-media-creatives', number: '05', title: 'Social Media Creatives', short: 'Stop the scroll with something worth stopping for.', description: 'Always-on creative systems that turn feeds into conversations and communities into growth.', image: 'https://images.pexels.com/photos/8546590/pexels-photo-8546590.jpeg?auto=compress&cs=tinysrgb&w=1200', icon: '#', subs: ['Instagram', 'Facebook', 'LinkedIn', 'Creative Campaigns'], process: ['Listen to the audience', 'Build content pillars', 'Create the rhythm', 'Learn and optimise'] },
  { slug: 'content-creation', number: '06', title: 'Content Creation', short: 'Say the thing in a way only you can.', description: 'Words and worlds that give your brand a point of view — from first line to final frame.', image: 'https://images.pexels.com/photos/8400601/pexels-photo-8400601.jpeg?auto=compress&cs=tinysrgb&w=1200', icon: 'Aa', subs: ['Copywriting', 'Scripts', 'Storytelling', 'Visual Content'], process: ['Find your voice', 'Tell the true story', 'Create the series', 'Keep it moving'] },
  { slug: 'web-design', number: '07', title: 'Web Design', short: 'Digital spaces with a pulse.', description: 'Expressive, intuitive websites that make beautiful first impressions and effortless next steps.', image: 'https://images.pexels.com/photos/12680818/pexels-photo-12680818.jpeg?auto=compress&cs=tinysrgb&w=1200', icon: '⌁', subs: ['Websites', 'UI/UX', 'Landing Pages', 'Creative Experiences'], process: ['Map the journey', 'Design the feeling', 'Build the flow', 'Launch the experience'] },
  { slug: 'motion-graphics', number: '08', title: 'Motion Graphics', short: 'Give your ideas a little more gravity.', description: 'Motion identities, explainers and visual systems that bring a static brand into a moving world.', image: 'https://images.pexels.com/photos/8339244/pexels-photo-8339244.jpeg?auto=compress&cs=tinysrgb&w=1200', icon: '◒', subs: ['Animated Posts', 'Logo Reveals', 'Explainer Videos', 'Advertisements'], process: ['Set the tempo', 'Sketch the movement', 'Animate the details', 'Make it sing'] },
  { slug: 'campaigns', number: '09', title: 'Campaigns', short: 'One idea. Everywhere it matters.', description: 'Integrated creative campaigns designed around real business objectives, not vanity metrics.', image: 'https://images.pexels.com/photos/9197509/pexels-photo-9197509.jpeg?auto=compress&cs=tinysrgb&w=1200', icon: '✳', subs: ['Launch Campaigns', 'Product Campaigns', 'Seasonal Campaigns', 'Integrated Ideas'], process: ['Define the objective', 'Build the platform', 'Orchestrate the channels', 'Grow the result'] },
  { slug: 'creative-strategy', number: '10', title: 'Creative Strategy', short: 'Make the right idea inevitable.', description: 'The clarity behind the creativity: what to communicate, how to say it and who needs to hear it.', image: 'https://images.pexels.com/photos/6214/hands-people-woman-girl.jpg?auto=compress&cs=tinysrgb&w=1200', icon: '⊙', subs: ['Brand Positioning', 'Audience Strategy', 'Content Strategy', 'Creative Direction'], process: ['Ask better questions', 'Find the sharp truth', 'Choose the territory', 'Give it direction'] },
  { slug: 'digital-marketing', number: '11', title: 'Digital Marketing', short: 'Turn attention into action.', description: 'Performance marketing that pairs creative instinct with useful data to move the metrics that matter.', image: 'https://images.pexels.com/photos/7691707/pexels-photo-7691707.jpeg?auto=compress&cs=tinysrgb&w=1200', icon: '⌁', subs: ['Run Ads', 'SEO', 'SMO / SMM', 'Remarketing Campaigns', 'Track Conversions'], process: ['Set the signal', 'Build the engine', 'Test the message', 'Scale what works'] },
];

export const projects = [
  { slug: 'neon-notes', title: 'Neon Notes', category: 'Branding', description: 'A new visual language for a culture-first music platform.', year: '2025', image: 'https://images.pexels.com/photos/8339244/pexels-photo-8339244.jpeg?auto=compress&cs=tinysrgb&w=1400' },
  { slug: 'the-good-table', title: 'The Good Table', category: 'Campaigns', description: 'A fresh campaign for food that brings people together.', year: '2025', image: 'https://images.pexels.com/photos/8546590/pexels-photo-8546590.jpeg?auto=compress&cs=tinysrgb&w=1400' },
  { slug: 'inside-the-frame', title: 'Inside the Frame', category: 'Video', description: 'A cinematic product story for the makers behind the lens.', year: '2024', image: 'https://images.pexels.com/photos/24286930/pexels-photo-24286930.jpeg?auto=compress&cs=tinysrgb&w=1400' },
  { slug: 'shape-of-now', title: 'Shape of Now', category: 'Motion', description: 'Motion language for a brand always in beta.', year: '2024', image: 'https://images.pexels.com/photos/9197509/pexels-photo-9197509.jpeg?auto=compress&cs=tinysrgb&w=1400' },
  { slug: 'new-perspective', title: 'New Perspective', category: 'Web', description: 'An editorial digital home for a modern design practice.', year: '2023', image: 'https://images.pexels.com/photos/12680818/pexels-photo-12680818.jpeg?auto=compress&cs=tinysrgb&w=1400' },
  { slug: 'made-to-move', title: 'Made to Move', category: 'Social Media', description: 'A social system that makes every day feel like a launch.', year: '2023', image: 'https://images.pexels.com/photos/4271625/pexels-photo-4271625.jpeg?auto=compress&cs=tinysrgb&w=1400' },
  { slug: 'signal-and-story', title: 'Signal & Story', category: 'Advertising', description: 'A performance campaign that made a complex product feel simple.', year: '2023', image: 'https://images.pexels.com/photos/7691707/pexels-photo-7691707.jpeg?auto=compress&cs=tinysrgb&w=1400' },
];

export const posts = [
  { slug: 'why-brands-need-a-point-of-view', category: 'Strategy', title: 'Why brands need a point of view, not just a visual identity', excerpt: 'The brands we remember have something to say — and the courage to say it consistently.', date: 'Sep 12, 2025', author: 'SolifyHub', image: 'https://images.pexels.com/photos/6224/hands-people-woman-working.jpg?auto=compress&cs=tinysrgb&w=1200', tags: ['branding', 'strategy', 'identity'] },
  { slug: 'the-new-rules-of-the-scroll', category: 'Social Media', title: 'The new rules of the scroll', excerpt: 'Attention is not a metric. It is an invitation. Here is how to make people want to stay.', date: 'Aug 28, 2025', author: 'Aarav Mehta', image: 'https://images.pexels.com/photos/15595050/pexels-photo-15595050.jpeg?auto=compress&cs=tinysrgb&w=1200', tags: ['social media', 'content', 'creative'] },
  { slug: 'designing-for-momentum', category: 'Design', title: 'Designing for momentum', excerpt: 'A practical look at the small systems that turn a good brand into a living one.', date: 'Jul 06, 2025', author: 'SolifyHub', image: 'https://images.pexels.com/photos/7180492/pexels-photo-7180492.jpeg?auto=compress&cs=tinysrgb&w=1200', tags: ['design', 'systems', 'branding'] },
  { slug: 'creative-that-converts', category: 'Marketing', title: 'Creative that converts is creative that connects', excerpt: 'Performance and brand are not opposites. The best work knows how to do both.', date: 'Jun 14, 2025', author: 'Nisha Rao', image: 'https://images.pexels.com/photos/97080/pexels-photo-97080.jpeg?auto=compress&cs=tinysrgb&w=1200', tags: ['marketing', 'advertising', 'growth'] },
  { slug: 'the-dashboard-is-not-the-strategy', category: 'Technology', title: 'The dashboard is not the strategy', excerpt: 'Better marketing starts with better questions, not more tabs, charts or numbers.', date: 'May 22, 2025', author: 'SolifyHub', image: 'https://images.pexels.com/photos/577195/pexels-photo-577195.jpeg?auto=compress&cs=tinysrgb&w=1200', tags: ['technology', 'strategy', 'analytics'] },
  { slug: 'make-room-for-the-big-idea', category: 'Creative', title: 'Make room for the big idea', excerpt: 'The strongest creative work begins when teams stop filling space and start creating meaning.', date: 'Apr 10, 2025', author: 'Aarav Mehta', image: 'https://images.pexels.com/photos/6592690/pexels-photo-6592690.jpeg?auto=compress&cs=tinysrgb&w=1200', tags: ['creative', 'campaigns', 'ideas'] },
];

export const navItems = ['About', 'Services', 'Work', 'Journal'];
export const contact = { phone: '86888 29033', email: 'info@solifysrinivasa.com', address: 'Door No. 49, 34-31/3, Main Rd, beside Masjid-E-Taj Bagh, Akkayyapalem, Visakhapatnam, Andhra Pradesh 530016' };
